spring:
  application:
    name: springai-demo
 
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:1b
#          model: llava
    
      init:
        pull-model-strategy: when-missing
        chat:
          additional-models:
            - llava  
    
  threads:
    virtual:
      enabled: true

#Propiedad para deshabilitar la creacion automatica del chatClient por parte de Spring     
#spring.ai.chat.client.enabled: false

#Propiedad que permite mostrar en las trazas el input del usuario
spring.ai.chat.client.observations.include-input: true
#Propiedad para que zipkin reciba el 100% de las trazas de llamadas
management.tracing.sampling.probability: 1

#Propiedades de actuator
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always      
      