spring:
  application:
    name: springai-demo
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:1b
          
    mcp:
      client:
        toolcallback:
          enabled: true
        type: SYNC
#        request-timeout: 30s
        sse:
          connections:
            usuarios:
              url: http://localhost:8081
        stdio:
#          root-change-notification: true
#          servers-configuration: classpath:/static/mcpServer.json # Configuracion con fichero externo en formato Claude Desktop
          connections:
            files:
              command: docker
              args:
                - 'run'
                - '-i'
                - '--rm'
                - '--mount'
                - 'type=bind,src=/home/simonrodriguez/test,dst=/projects/test'
                - 'mcp/filesystem'
                - '/projects/test'
    
  threads:
    virtual:
      enabled: true
