spring:
  application:
    name: springai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:1b
    
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000
        initialize-schema: true
    
  threads:
    virtual:
      enabled: true

#Propiedad para deshabilitar la creacion automatica del chatClient por parte de Spring     
#spring.ai.chat.client.enabled: false

#Propiedad que permite mostrar en las trazas el input del usuario
spring.ai.chat.client.observations.include-input: true
#Propiedad para que zipkin reciba el 100% de las trazas de llamadas
management.tracing.sampling.probability: 1

#Propiedades de actuator
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always      
      